# Generated by Django 4.2.3 on 2023-07-20 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('1', 'Lahore'), ('2', 'Islamabad'), ('3', 'Karachi'), ('4', 'Multan'), ('5', 'Quetta'), ('6', 'Peshawar'), ('7', 'Hyderabad')], max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('price', models.CharField(default='0', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
