# Generated by Django 4.2.3 on 2024-01-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
