# Generated by Django 4.2.3 on 2024-01-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cartproduct_color_cartproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
