# Generated by Django 4.2.3 on 2023-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_catagory',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_pk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
