# Generated by Django 4.2.3 on 2023-07-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('dispatched', 'dispatched'), ('canceled', 'canceled')], default='pending', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_un_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
