# Generated by Django 4.2.3 on 2023-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_order_order_status_order_order_un_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('dispatched', 'dispatched'), ('canceled', 'canceled')], default='pending', max_length=10),
        ),
    ]
