# Generated by Django 4.2.2 on 2023-07-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_size',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
