# Generated by Django 4.2.2 on 2023-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('dispatched', 'dispatched'), ('canceled', 'canceled'), ('received', 'received')], default='pending', max_length=10),
        ),
    ]
