# Generated by Django 4.2.3 on 2023-12-22 21:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_article', models.CharField(default='-------', max_length=30, unique=True)),
                ('product_qty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_color', models.CharField(blank=True, default='None', max_length=30)),
                ('product_category', models.CharField(choices=[('M', 'M'), ('W', 'W'), ('B', 'B'), ('G', 'G')], default='', max_length=1)),
                ('product_clothing_type', models.CharField(choices=[('PANTS', 'PANTS'), ('SHORTS', 'SHORTS'), ('TSHIRTS', 'T-SHIRTS'), ('SHIRTS', 'SHIRTS'), ('TROUSERS', 'TROUSERS'), ('SHOES', 'SHOES'), ('SWEATSHIRTS', 'SWEATSHIRTS'), ('HOODIES', 'HOODIES'), ('SWEATERS', 'SWEATERS'), ('JACKETS', 'JACKETS'), ('JEANS', 'JEANS'), ('ACTIVEWEAR', 'ACTIVEWEAR'), ('ACCESSORIES', 'ACCESSORIES')], default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='undefined size', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClothingImages',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='products_images/')),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.clothing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clothing',
            name='product_size',
            field=models.ManyToManyField(to='store.size'),
        ),
        migrations.CreateModel(
            name='ClothingSizeQuantity',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.clothing')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size')),
            ],
            options={
                'unique_together': {('clothing', 'size')},
            },
        ),
    ]
