# Generated by Django 4.2.3 on 2023-12-23 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_article', models.CharField(default='-------', max_length=30, unique=True)),
                ('product_category', models.CharField(choices=[('M', 'M'), ('W', 'W'), ('B', 'B'), ('G', 'G')], default='', max_length=1)),
                ('product_clothing_type', models.CharField(choices=[('PANTS', 'PANTS'), ('SHORTS', 'SHORTS'), ('TSHIRTS', 'T-SHIRTS'), ('SHIRTS', 'SHIRTS'), ('TROUSERS', 'TROUSERS'), ('SHOES', 'SHOES'), ('SWEATSHIRTS', 'SWEATSHIRTS'), ('HOODIES', 'HOODIES'), ('SWEATERS', 'SWEATERS'), ('JACKETS', 'JACKETS'), ('JEANS', 'JEANS'), ('ACTIVEWEAR', 'ACTIVEWEAR'), ('ACCESSORIES', 'ACCESSORIES')], default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('size_name', models.CharField(default='undefined size', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=15)),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clothing', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_size', to='store.clothing')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingImages',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('clothing', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.clothing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClothingColors',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('clothing', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_color', to='store.clothing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
