# Generated by Django 4.2.3 on 2023-12-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingimages',
            name='clothing',
        ),
        migrations.AlterUniqueTogether(
            name='clothingsizequantity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clothingsizequantity',
            name='clothing',
        ),
        migrations.RemoveField(
            model_name='clothingsizequantity',
            name='size',
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
        migrations.DeleteModel(
            name='ClothingImages',
        ),
        migrations.DeleteModel(
            name='ClothingSizeQuantity',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
