# Generated by Django 4.2.3 on 2023-07-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='boys',
            name='gender',
            field=models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('B', 'BOYS'), ('G', 'GIRLS')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='girls',
            name='gender',
            field=models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('B', 'BOYS'), ('G', 'GIRLS')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='men',
            name='gender',
            field=models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('B', 'BOYS'), ('G', 'GIRLS')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='women',
            name='gender',
            field=models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('B', 'BOYS'), ('G', 'GIRLS')], default='W', max_length=1),
        ),
    ]
