# Generated by Django 4.2.3 on 2023-12-23 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingColors',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Size',
            new_name='ClothingSize',
        ),
        migrations.RenameField(
            model_name='clothingsize',
            old_name='name',
            new_name='size_name',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='product_color',
        ),
        migrations.AddField(
            model_name='clothing',
            name='product_color',
            field=models.ManyToManyField(to='store.clothingcolors'),
        ),
    ]
