# Generated by Django 4.2.3 on 2023-12-23 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_clothingcolors_rename_size_clothingsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='product_qty',
        ),
        migrations.AddField(
            model_name='clothingsize',
            name='size_qty',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='ClothingSizeQuantity',
        ),
    ]
