# Generated by Django 4.2.3 on 2023-07-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_order_boys_gender_girls_gender_men_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boys',
            old_name='gender',
            new_name='catagory',
        ),
        migrations.RenameField(
            model_name='girls',
            old_name='gender',
            new_name='catagory',
        ),
        migrations.RenameField(
            model_name='men',
            old_name='gender',
            new_name='catagory',
        ),
        migrations.RenameField(
            model_name='women',
            old_name='gender',
            new_name='catagory',
        ),
    ]
