# Generated by Django 4.2.3 on 2023-07-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviews_remove_reviews_g_post_remove_reviews_g_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews_w',
        ),
    ]
