# Generated by Django 4.2.3 on 2023-07-22 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_reviews_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='type',
            field=models.CharField(choices=[('PANTS', 'PANTS'), ('SHORTS', 'SHORTS'), ('T-SHIRTS', 'T-SHIRTS'), ('SHIRTS', 'SHIRTS'), ('TROUSERS', 'TROUSERS')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='women',
            name='type',
            field=models.CharField(choices=[('PANTS', 'PANTS'), ('SHORTS', 'SHORTS'), ('T-SHIRTS', 'T-SHIRTS'), ('SHIRTS', 'SHIRTS'), ('TROUSERS', 'TROUSERS')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='men',
            name='image',
            field=models.ImageField(upload_to='m_images/'),
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('article', models.CharField(default='-------', max_length=30, unique=True)),
                ('qty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(blank=True, default='None', max_length=30)),
                ('catagory', models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('B', 'BOYS'), ('G', 'GIRLS')], default='M', max_length=1)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.adult_size')),
            ],
        ),
    ]
