# Generated by Django 4.2.3 on 2023-07-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_men_type_women_type_alter_men_image_footwear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwear',
            name='catagory',
            field=models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('B', 'BOYS'), ('G', 'GIRLS')], max_length=1),
        ),
    ]
