# Generated by Django 4.2.3 on 2023-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_men_type_alter_women_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='type',
            field=models.CharField(choices=[('PANTS', 'PANTS'), ('SHORTS', 'SHORTS'), ('TSHIRTS', 'T-SHIRTS'), ('SHIRTS', 'SHIRTS'), ('TROUSERS', 'TROUSERS')], max_length=8),
        ),
        migrations.AlterField(
            model_name='women',
            name='type',
            field=models.CharField(choices=[('PANTS', 'PANTS'), ('SHORTS', 'SHORTS'), ('TSHIRTS', 'T-SHIRTS'), ('SHIRTS', 'SHIRTS'), ('TROUSERS', 'TROUSERS')], max_length=8),
        ),
    ]
