# Generated by Django 4.2.2 on 2023-07-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_men_type_alter_women_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='men',
            old_name='type',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='women',
            old_name='type',
            new_name='product_type',
        ),
    ]
