# Generated by Django 4.2.2 on 2023-07-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_type_men_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='men',
            name='size',
        ),
        migrations.AddField(
            model_name='men',
            name='size',
            field=models.ManyToManyField(to='store.adult_size'),
        ),
    ]
