# Generated by Django 4.2.2 on 2023-07-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_men_size_men_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boys',
            name='size',
        ),
        migrations.RemoveField(
            model_name='girls',
            name='size',
        ),
        migrations.RemoveField(
            model_name='women',
            name='size',
        ),
        migrations.AddField(
            model_name='boys',
            name='size',
            field=models.ManyToManyField(to='store.minor_size'),
        ),
        migrations.AddField(
            model_name='girls',
            name='size',
            field=models.ManyToManyField(to='store.minor_size'),
        ),
        migrations.AddField(
            model_name='women',
            name='size',
            field=models.ManyToManyField(to='store.adult_size'),
        ),
    ]
