# Generated by Django 4.2.2 on 2023-07-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_boys_size_remove_girls_size_remove_women_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footwear',
        ),
    ]
