# Generated by Django 4.2.3 on 2023-12-17 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_footwear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('article', models.CharField(default='-------', max_length=30, unique=True)),
                ('qty', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(blank=True, default='None', max_length=30)),
                ('category', models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN'), ('B', 'BOYS'), ('G', 'GIRLS')], default='', max_length=1)),
                ('age_group', models.CharField(choices=[('A', 'Adult'), ('M', 'Minor')], default='', max_length=1)),
                ('clothing_type', models.CharField(choices=[('PANTS', 'PANTS'), ('SHORTS', 'SHORTS'), ('TSHIRTS', 'T-SHIRTS'), ('SHIRTS', 'SHIRTS'), ('TROUSERS', 'TROUSERS'), ('SHOES', 'SHOES')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined size', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='boys',
            name='size',
        ),
        migrations.RemoveField(
            model_name='girls',
            name='size',
        ),
        migrations.RemoveField(
            model_name='men',
            name='size',
        ),
        migrations.RemoveField(
            model_name='women',
            name='size',
        ),
        migrations.DeleteModel(
            name='Adult_size',
        ),
        migrations.DeleteModel(
            name='Boys',
        ),
        migrations.DeleteModel(
            name='Girls',
        ),
        migrations.DeleteModel(
            name='Men',
        ),
        migrations.DeleteModel(
            name='Minor_size',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
        migrations.AddField(
            model_name='clothing',
            name='size',
            field=models.ManyToManyField(to='store.sizes'),
        ),
    ]
