# Generated by Django 4.2.3 on 2023-12-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_clothing_sizes_remove_boys_size_remove_girls_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(choices=[('M', 'M'), ('W', 'W'), ('B', 'B'), ('G', 'G')], default='', max_length=1),
        ),
    ]
