# Generated by Django 4.2.3 on 2023-12-22 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_clothing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingSizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.clothing')),
            ],
        ),
        migrations.RenameModel(
            old_name='sizes',
            new_name='Size',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='clothingsizequantity',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size'),
        ),
        migrations.AlterUniqueTogether(
            name='clothingsizequantity',
            unique_together={('clothing', 'size')},
        ),
    ]
