# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code

# Copy the requirements file to the container
COPY urbanthreads/requirements.txt /code/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire Django project to the container
COPY urbanthreads /code/

# Replace '/code/manage.py' with the actual path to your manage.py file
# Execute Django collectstatic (if needed) and migrate commands during the build
RUN python manage.py collectstatic --noinput
RUN python manage.py migrate

# Expose the port on which your Django app runs
EXPOSE 8000

# Define the command to start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
